package-analytics/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package-analytics/main/default/objects/Package__c/fields/LastUpdated__c.field-meta.xml
<CustomField>
    <fullName>LastUpdated__c</fullName>
    <label>Last Updated</label>
    <type>DateTime</type>
</CustomField>

package-analytics/main/default/objects/Package__c/fields/NamespacePrefix__c.field-meta.xml
<CustomField>
    <fullName>NamespacePrefix__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

package-analytics/main/default/objects/Package__c/fields/PackageCategory__c.field-meta.xml
<CustomField>
    <fullName>PackageCategory__c</fullName>
    <label>Package Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Package2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

package-analytics/main/default/objects/Package__c/fields/PackageId__c.field-meta.xml
<CustomField>
    <fullName>PackageId__c</fullName>
    <externalId>true</externalId>
    <label>Package ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/PackageSubscriberOrg__c.object-meta.xml
<CustomObject>
    <label>Package Subscriber Org</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Subscriber Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/InstalledStatus__c.field-meta.xml
<CustomField>
    <fullName>InstalledStatus__c</fullName>
    <label>Installed Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/InstanceName__c.field-meta.xml
<CustomField>
    <fullName>InstanceName__c</fullName>
    <label>Instance Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/OrgId__c.field-meta.xml
<CustomField>
    <fullName>OrgId__c</fullName>
    <externalId>true</externalId>
    <label>Org ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/OrgStatus__c.field-meta.xml
<CustomField>
    <fullName>OrgStatus__c</fullName>
    <label>Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/OrgType__c.field-meta.xml
<CustomField>
    <fullName>OrgType__c</fullName>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <color>#009900</color>
                <label>Production</label>
            </value>
            <value>
                <fullName>Sandbox</fullName>
                <color>#3366FF</color>
                <label>Sandbox</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/PackageSubscriberId__c.field-meta.xml
<CustomField>
    <fullName>PackageSubscriberId__c</fullName>
    <externalId>true</externalId>
    <label>Package Subscriber ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/PackageVersion__c.field-meta.xml
<CustomField>
    <fullName>PackageVersion__c</fullName>
    <label>Package Version</label>
    <referenceTo>PackageVersion__c</referenceTo>
    <relationshipLabel>Package Installs</relationshipLabel>
    <relationshipName>PackageSubscriberOrgs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/ParentOrg__c.field-meta.xml
<CustomField>
    <fullName>ParentOrg__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Org</label>
    <referenceTo>PackageSubscriberOrg__c</referenceTo>
    <relationshipLabel>Related Orgs</relationshipLabel>
    <relationshipName>RelatedOrgs</relationshipName>
    <type>Lookup</type>
</CustomField>

package-analytics/main/default/objects/PackageSubscriberOrg__c/fields/ParentOrgId__c.field-meta.xml
<CustomField>
    <fullName>ParentOrgId__c</fullName>
    <label>Parent Org ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/PackageVersion__c.object-meta.xml
<CustomObject>
    <label>Package Version</label>
    <nameField>
        <label>Package Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

package-analytics/main/default/objects/PackageVersion__c/fields/BuildNumber__c.field-meta.xml
<CustomField>
    <fullName>BuildNumber__c</fullName>
    <label>Build Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/IsDeprecated__c.field-meta.xml
<CustomField>
    <fullName>IsDeprecated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deprecated</label>
    <type>Checkbox</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/MajorVersion__c.field-meta.xml
<CustomField>
    <fullName>MajorVersion__c</fullName>
    <label>Major Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/MinorVersion__c.field-meta.xml
<CustomField>
    <fullName>MinorVersion__c</fullName>
    <label>Minor Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Package Versions</relationshipLabel>
    <relationshipName>PackageVersions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/PatchVersion__c.field-meta.xml
<CustomField>
    <fullName>PatchVersion__c</fullName>
    <label>Patch Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/ReleaseState__c.field-meta.xml
<CustomField>
    <fullName>ReleaseState__c</fullName>
    <label>Release State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

package-analytics/main/default/objects/PackageVersion__c/fields/SubscriberPackageVersionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberPackageVersionId__c</fullName>
    <externalId>true</externalId>
    <label>Subscriber Package Version ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

package-analytics/main/default/classes/PackageExtractJob.cls
/*
  The SObjects `MetadataPackage`, `MetadataPackageVersion`, and `PackageSubscriber` don't exist in all orgs,
  including scratch orgs - this class uses Strings, dyanmic Apex & dynamic SOQL so this can be bundled into a 2GP
*/

public without sharing class PackageExtractJob implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
  private static final Integer BATCH_SIZE = 2000;

  @TestVisible
  private Integer queryLimit;
  @TestVisible
  private Boolean willRunAnotherTime = false;
  @TestVisible
  private List<String> sobjectNames = new List<String>{
    'MetadataPackage',
    'MetadataPackageVersion',
    'PackageSubscriber'
  };

  public void scheduleHourly() {
    System.schedule('Hourly Package Data Extract Job', '0 0 * * * ?', this);
  }

  public void execute(System.SchedulableContext context) {
    Database.executeBatch(this, BATCH_SIZE);
  }

  public Database.QueryLocator start(Database.BatchableContext context) {
    String currentSObjectName = this.sobjectNames.remove(0);
    return getQueryLocator(currentSObjectName);
  }

  public void execute(Database.BatchableContext context, List<SObject> scope) {
    String currentSObjectName = scope.get(0).getSObjectType().getDescribe().getName();

    switch on currentSObjectName {
      when 'MetadataPackage' {
        this.processPackages(scope);
      }
      when 'MetadataPackageVersion' {
        this.processPackageVersions(scope);
      }
      when 'PackageSubscriber' {
        this.processPackageSubscribers(scope);
      }
    }
  }

  public void finish(Database.BatchableContext context) {
    if (this.sobjectNames.isEmpty() == false) {
      this.willRunAnotherTime = true;
      if (Test.isRunningTest() == false) {
        Database.executeBatch(this, BATCH_SIZE);
      }
    }
  }

  private Database.QueryLocator getQueryLocator(String sobjectName) {
    String query;
    switch on sobjectName {
      when 'MetadataPackage' {
        query = 'SELECT Id, Name, NamespacePrefix, PackageCategory, SystemModStamp FROM MetadataPackage';
      }
      when 'MetadataPackageVersion' {
        query = 'SELECT BuildNumber, Id, IsDeprecated, MajorVersion, MetadataPackageid, MinorVersion, Name, PatchVersion, ReleaseState, SystemModStamp FROM MetadataPackageVersion';
      }
      when 'PackageSubscriber' {
        query = 'SELECT Id, InstalledStatus, InstanceName, MetadataPackageId, MetadataPackageVersionId, OrgKey, OrgName, OrgStatus, OrgType, ParentOrg, SystemModStamp FROM PackageSubscriber';
      }
      when else {
        Exception ex = new IllegalArgumentException();
        ex.setMessage('Unsupported SObjectType: ' + sobjectName);
        throw ex;
      }
    }

    if (this.queryLimit != null) {
      query += ' LIMIT ' + this.queryLimit;
    }
    return Database.getQueryLocator(query);
  }

  private void processPackages(List<SObject> metadataPackages) {
    List<Package__c> packages = new List<Package__c>();
    for (SObject metadataPackage : metadataPackages) {
      packages.add(
        new Package__c(
          LastUpdated__c = (Datetime) metadataPackage.get('SystemModStamp'),
          PackageCategory__c = (String) metadataPackage.get('PackageCategory'),
          PackageId__c = Id.valueOf((String) metadataPackage.get('Id')),
          Name = (String) metadataPackage.get('Name'),
          NamespacePrefix__c = (String) metadataPackage.get('NamespacePrefix')
        )
      );
    }
    upsert packages PackageId__c;
  }

  private void processPackageVersions(List<SObject> metadataPackageVersions) {
    List<PackageVersion__c> packageVersions = new List<PackageVersion__c>();
    for (SObject metadataPackageVersion : metadataPackageVersions) {
      packageVersions.add(
        new PackageVersion__c(
          BuildNumber__c = (Decimal) metadataPackageVersion.get('BuildNumber'),
          IsDeprecated__c = (Boolean) metadataPackageVersion.get('IsDeprecated'),
          LastUpdated__c = (Datetime) metadataPackageVersion.get('SystemModStamp'),
          MajorVersion__c = (Decimal) metadataPackageVersion.get('MajorVersion'),
          MinorVersion__c = (Decimal) metadataPackageVersion.get('MinorVersion'),
          Name = truncateFieldValue(Schema.PackageVersion__c.Name, (String) metadataPackageVersion.get('Name')),
          Package__r = new Package__c(
            PackageId__c = Id.valueOf((String) metadataPackageVersion.get('MetadataPackageId'))
          ),
          PatchVersion__c = (Decimal) metadataPackageVersion.get('PatchVersion'),
          ReleaseState__c = (String) metadataPackageVersion.get('ReleaseState'),
          SubscriberPackageVersionId__c = Id.valueOf((String) metadataPackageVersion.get('Id'))
        )
      );
    }
    upsert packageVersions SubscriberPackageVersionId__c;
  }

  private void processPackageSubscribers(List<SObject> packageSubscribers) {
    Map<String, PackageSubscriberOrg__c> parentSubscriberOrgsByOrgId = new Map<String, PackageSubscriberOrg__c>();
    Map<String, PackageSubscriberOrg__c> childSubscriberOrgsByOrgId = new Map<String, PackageSubscriberOrg__c>();

    for (SObject packageSubscriber : packageSubscribers) {
      PackageSubscriberOrg__c org = new PackageSubscriberOrg__c(
        InstalledStatus__c = (String) packageSubscriber.get('InstalledStatus'),
        InstanceName__c = (String) packageSubscriber.get('InstanceName'),
        LastUpdated__c = (Datetime) packageSubscriber.get('SystemModStamp'),
        Name = (String) packageSubscriber.get('OrgName'),
        OrgId__c = Id.valueOf((String) packageSubscriber.get('OrgKey')),
        OrgStatus__c = (String) packageSubscriber.get('OrgStatus'),
        OrgType__c = (String) packageSubscriber.get('OrgType'),
        PackageSubscriberId__c = Id.valueOf((String) packageSubscriber.get('Id')),
        PackageVersion__r = new PackageVersion__c(
          SubscriberPackageVersionId__c = Id.valueOf((String) packageSubscriber.get('MetadataPackageVersionId'))
        )
      );
      if (packageSubscriber.get('ParentOrg') == null) {
        parentSubscriberOrgsByOrgId.put(org.OrgId__c, org);
      } else {
        org.ParentOrgId__c = Id.valueOf((String) packageSubscriber.get('ParentOrg'));
        childSubscriberOrgsByOrgId.put(org.OrgId__c, org);
      }
    }

    // Parent orgs
    upsert parentSubscriberOrgsByOrgId.values() OrgId__c;

    // Child orgs
    for (PackageSubscriberOrg__c childOrg : childSubscriberOrgsByOrgId.values()) {
      if (parentSubscriberOrgsByOrgId.containsKey(childOrg.ParentOrgId__c) == true) {
        childOrg.ParentOrg__c = parentSubscriberOrgsByOrgId.get(childOrg.ParentOrgId__c).Id;
      }
    }
    upsert childSubscriberOrgsByOrgId.values() OrgId__c;
  }

  private static String truncateFieldValue(Schema.SObjectField field, String value) {
    Integer fieldMaxLength = field.getDescribe().getLength();
    return value?.left(fieldMaxLength);
  }
}